get /signup

to signup as new user or admain 

*body*
``` 
  {    
     "username":"string",   
    "password":"****",   
    "role":"admin/user"   
   } 
   ```
    


post /signin   
to signinas user or admain    

*body*
```
  {    
     "username":"string",   
    "password":"****",   
     
   }
```
GET url HTTP/1.1/signout  
   to signout

////////////////     auth////////////////////////////////

delete /delete/:username
enable admin to delete users    

**put**  /user/profile/:id/update    

to update user profile 

*body*    
```
{
    "username": "admin",  
    "role": "admin",   
    "firstName": "mmmm",   
    "lastName": "bbbb",   
    "phoneNumber": "07",   
    "email": "hotmail",   
    "city": "Irbid"   
}
```   

///////////vistitorrou/////////

get /:model  
Get specific model posts (visitor)





